const names = [
"Jiří Šimšálek",
"Lenka Landryová",
"Tomáš Pindur",
"Vojtěch Aberle",
"Kateřina Lalíková",
"Kateřina Lalíková",
"Jakub Moldrzyk",
"Jan Hikl",
"Jan Hikl",
"Pavel Eschler",
"Daniel Otáhal",
"Daniel Otáhal",
"Daniel Otáhal",
"Daniel Otáhal",
"Daniel Otáhal",
"Veronika Weissová",
"Jan Lacina",
"Radoslav Delinčák",
"Motaz Saleh",
"Pavel Spinka",
"Aneta Michulková",
"Beata Pierchalová",
"Ivana Dehnerova",
"Ivana Dehnerova",
"Martin Mondřík",
"Martin Mondřík",
"Martin Mondřík",
"Martin Mondřík",
"Radim Břenek",
"Michal Ferko",
"Michal Ferko",
"Michal Paszek",
"Michael Bik",
"Moataz Saleh",
"Martin Mondřík",
"Martin Stanovsky",
"Jiří Hradil",
"Katerina Hudkova",
"Melih KARAALI",
"Melih KARAALI",
"Melih KARAALI",
"Petr Skalnicky",
"Marie Seltenreich",
"Marie Seltenreich",
"Jan Karhánek",
"Lenka Štěpánová",
"Jakub Kalouda",
"Lukáš Krais",
"Klára Blechová",
"Martin Albert",
"Monika BRAZDOVA",
"Aleksandar Čebzan",
"Tomas Larys",
"AMR ALAA",
"AMR ALAA",
"AMR ALAA",
"Nikola Kovacevic",
"Martin Dvorak",
"Yevgeniy Sizov",
"Tomas Dockal",
"Tomas Dockal",
"Tomas Dockal",
"Martin Veselý",
"Martin Veselý",
"Žaneta Šinkovicová Sojková",
"Eva Konakovska",
"Tomas Larys",
"Jiří Kováč",
"Žaneta Šinkovicová Sojková",
"David Polok",
"Lucia Lajčáková",
"Mohamed ATIA",
"Natasa Sabo",
"Ondřej Korbela",
"Samuel Gabaj",
"Martin Greňo",
"Aleš Vašíček",
"Samuel Gabaj",
"Ondřej Korbela",
"Vojtěch Kaniok",
"Radek Škrla",
"Lucie Kosíková",
"Lucie Kosíková",
"Vojtěch Kaniok",
"Renáta Škrlíková",
"Renáta Škrlíková",
"Vojtech Ulmann",
"Zdenek Oborny",
"Jakub Szebesta",
"walter stricker",
"walter stricker",
"Alena Becvarova",
"Mohamed ATIA",
"Jiří Novák",
"Alena Becvarova",
"Martin Greňo",
"Lazar Lazarevic",
"Tomas Dockal",
"Michal Novák",
"Daniel Balhar",
"Jakub Samek",
"Jiří Lacek",
"Lenka Dudková",
"Klára Navrátilová",
"Roman Novák",
"Katarina Urbanova",
"Tereza Hlavoňová Fialová",
"Adam Goranov",
"Kristina Gabrisova",
"Boháčová Radka",
"Jakub Martásek",
"Petra Křenová",
"Petra Křenová",
"Nikola Kovacevic",
"Karolína Staňková",
"Rostislav Fiala",
"Lukas Rucky",
"Tomáš Hanuška",
"Premysl KOSTKA",
"Radim Břenek",
"Lucie Pyšová",
"Lukáš Kuruc",
"Veronika WEISSOVA",
"Martin Kompanek",
"Ondřej Korbela",
"Hana Chalupová",
"Jan Stodola",
"Andrea Pikova",
"Andrea Pikova",
"Monika Göçeri",
"Monika Göçeri",
"Monika Göçeri",
"Moataz Saleh",
"Kamila Šponerová",
"Katerina Nova",
"Daniel Lyčka",
"Mladen Kasler",
"Vojtech Polasek",
"Daniel Balhar",
"Matěj Glogar",
"Jiri Stulik",
"Marie Seltenreich",
"Tomáš Paseka",
"Frantisek DOPITA",
"jiri Pavlinec",
"Moataz Saleh",
"Moataz Saleh",
"Radek Linhart",
"Martin Pokrivčák",
"Radek Kovařík",
"Monika Banotova",
"Marie Seltenreich",
"Jolana Janáková",
"Ondřej Korbela",
"Jakub Šlachta",
"Moataz Saleh",
"Moataz Saleh",
"Matěj Glogar",
"Michaela Knopova",
"Monika Banotova",
"Ondřej Konečný",
"Daniel Balhar",
"Kateřina Burdíková",
"Marie Seltenreich",
"Jakub Samek",
"Lazar Lazarevic",
"AMR ALAA",
"Matěj Glogar",
"Dominik Urbančík",
"Marie Seltenreich",
"Renata Skowranková",
"Miroslav Jurosz",
"Moataz Saleh",
"Vojtěch Liberda",
"Veronika WEISSOVA",
"Radim Havlásek",
"Jakub Ministr",
"Jiří Klimeš",
"Veronika WEISSOVA",
"Tadeáš Bařina",
"Martin Kompanek",
"Matej Sudek",
"Michaela Knopova",
"Michaela Knopova",
"erkut tokman",
"Vojtěch Lyčka",
"Jiri Galacz",
"Miroslav Kamenský",
"Jiri Galacz",
"Ondřej Korbela",
"Martin Pokrivčák",
"Lukáš Klhůfek",
"Adam Krása",
"Jana Hachemi",
"Paula GORGE",
"Paula GORGE",
"Paula GORGE",
"Paula GORGE",
"Paula GORGE",
"Paula GORGE",
"Paula GORGE",
"Vojtech Ulmann",
"Andrea Pikova",
"Andrea Pikova",
"Radovan Čierný",
"Mladen Kasler",
"Mladen Kasler",
"Premysl KOSTKA",
"Lukas Rucky",
"Pavlína Rybecká",
"Lukas Pokorny",
"Dominik Urbančík",
"Pavel Dvořák",
"Katerina Nova",
"Premysl KOSTKA",
"Boyan Atanasov",
"Šárka Magnusková",
"Nikola Tillova",
"Marek Gruzovský",
"Aliaksandr SIROTSIN",
"Josef Šustek",
"Aliaksandr SIROTSIN",
"Aliaksandr SIROTSIN",
"Zuzana Klimsova",
"Anton Duda",
"Paula GORGE",
"Paula GORGE",
"Dominik Lanča",
"Oksana NEBOHA",
"Oksana NEBOHA",
"Yevgeniy Sizov",
"AMR ALAA",
"Kateřina Lalíková",
"Peter Papánek",
"Paula GORGE",
"Yevgeniy Sizov",
"Nikola Mik Bahrová",
"Tomas Larys",
"Aneta Teichmannová",
"Eva Moyalova",
"Eva Moyalova",
"Eva Moyalova",
"AMR ALAA",
"Lukas Bartoš",
"Jindřich Šonka",
"Tomáš Hlinovský",
"Jiří Plíšek",
"Beata Pierchalova",
"Beata Pierchalova",
"Lucia",
"Lazar Lazarevic",
"Lukáš Krais",
"Martina Prokešová",
"Petr Vantuch",
"Dmitrii Maksimov",
"AMR ALAA",
"Ondřej Horsky",
"Martina Prokešová",
"Lenka ZAPLETALOVA",
"Denisa Weinhold",
"Jakub Moldrzyk",
"Jakub Moldrzyk",
"Anton Duda",
"Ondřej Korbela",
"Lenka ZAPLETALOVA",
"Lazar Lazarevic",
"HASSAN MOHAMMED HASSAN IBRAHIM",
"Nikola Mik Bahrová",
"Mohamed Yehia Ibrahim",
"Miroslav Jurosz",
"Mohamed Yehia Ibrahim",
"HASSAN MOHAMMED HASSAN IBRAHIM",
"HASSAN MOHAMMED HASSAN IBRAHIM",
"Moataz Saleh",
"Martin Karvánek",
"Kamila Šponerová",
"Miroslav Sameš",
"Adam Krása",
"Adam Krása",
"Bohdana Bajgerova",
"Adam Krása",
"Aliaksandr SIROTSIN",
"Aliaksandr SIROTSIN",
"Aliaksandr SIROTSIN",
"Aliaksandr SIROTSIN",
"Lenka Landryová",
"Veronika WEISSOVA",
"Veronika WEISSOVA",
"Veronika WEISSOVA",
"Anton Duda",
"Veronika Herudková",
"Anton Duda",
"Anton Duda",
"Luboš Kelnar",
"Tomas Larys",
"Miroslav Jurosz",
"Jana Stárková",
"Lazar Lazarevic",
"Jiří Klimeš",
"Alexander Práznovský",
"Matouš Vrzala",
"Ondrej Francik",
"Matouš Vrzala",
"Anton Duda",
"Anton Duda",
"Veronika WEISSOVA",
"Martin Kaszper",
"Jana Grafová",
"Abrorkhon Akhmedov",
"Abrorkhon Akhmedov",
"Abrorkhon Akhmedov",
"Tomas Larys",
"Milan Synek",
"Aliaksandr SIROTSIN",
"Lenka ZAPLETALOVA",
"Aliaksandr SIROTSIN",
"Marcela Boniatti",
"Jana Hachemi",
"Jana Hachemi",
"Veronika ONDERKOVA",
"Pavel Šimíček",
"Lazar Lazarevic",
"Petr Stodůlka",
"Vladislav Rodionov",
"Jana Hachemi",
"Michal Nevlud",
"Michal Nevlud",
"Petr Stodůlka",
"Jan Ungr",
"Lukáš Krais",
"Daniel Balhar",
"Lazar Lazarevic",
"Adam Krása",
"Miroslav Jurosz",
"Richard Joseph CONAWAY",
"Adam Krása",
"Adam Krása",
"Radim Lapiš",
"Radim Lapiš",
"Pavel Špinka",
"Adam Johann Luzar",
"Křibík",
"Robert Stodulka",
"HASSAN MOHAMMED HASSAN IBRAHIM",
"HASSAN MOHAMMED HASSAN IBRAHIM",
"HASSAN MOHAMMED HASSAN IBRAHIM",
"Jan Žižlavský",
"Radim Lapiš",
"Radim Lapiš",
"Vojtěch Kalas",
"Martin Kaszper",
"Jakub Hlavica",
"Radim Havlásek",
"Veronika ONDERKOVA",
"Adéla Sznapková",
"Jan Kantor",
"Lucia",
"HASSAN MOHAMMED HASSAN IBRAHIM",
"Jan Kantor",
"Petr Korbel",
"Petr Korbel",
"Eva Suchá",
"Tomas Larys",
"Richard Papřok",
"Eliška Masná",
"Eliška Masná",
"HASSAN MOHAMMED HASSAN IBRAHIM",
"Pavel SKOP",
"Zaur Hamzayev",
"Jiří Hradil",
"Radoslav Delinčák",
"Adam Johann Luzar",
"Adam Johann Luzar",
"Tereza Hlavoňová Fialová",
"Anton Duda",
"Peter Rainhard Schuster",
"Dallas Bond",
"Katerina Hudkova",
"Petr Záhejský",
"Markéta Pindryčová",
"Lenka ZAPLETALOVA",
"Jan Baťka",
"Jan Kantor",
"Mikuláš Čajánek",
"Alireza",
"David Farník",
"Matěj Malysa",
"Radim Lapiš",
"Peter Bdzoch",
"Petr Stodůlka",
"Vojtěch Kubíček",
"Kateřina Lalíková",
"Aneta Michulková",
"Marek Czopnik",
"Matěj Malysa",
"Radomir Liška",
"Hana Stefanov",
"Marek Gruzovský",
"Irena Škrlíková",
"Jiri Kula",
"Jiri Kula",
"Beata Pierchalova",
"Lenka ZAPLETALOVA",
"AMR ALAA",
"Aliaksandr SIROTSIN",
"Aliaksandr SIROTSIN",
"Aliaksandr SIROTSIN",
"Aliaksandr SIROTSIN",
"Pavla Žaroská",
"Matouš Vrzala",
"Patrik Kubalík",
"Patrik Kubalík",
"Ingrid Papež",
"Richard Vágner",
"Richard Vágner",
"Lucie Pyšová",
"Lucie Pyšová",
"Luboš Kelnar",
"Tadeáš Bařina",
"Jana Grafová",
"Ingrid Papež",
"Matouš Vrzala"
]

// Selectors
const candidatesButton = document.querySelector(".btn");
const candidates = document.querySelector(".candidates");

// Events
candidatesButton.addEventListener("click", getRandomCandidate);

// functions

function getRandomCandidate(event) {
    event.preventDefault();
    const randomNumber = Math.floor(Math.random() * names.length);  

    // Create LI
    const newCandidate = document.createElement("li");
    newCandidate.innerText = names[randomNumber];
    newCandidate.classList.add("newCandidate");

    // Append LI to UL
    candidates.appendChild(newCandidate);
    console.log(names);
    names.splice(randomNumber, 1)
}




