const names = [
    "Adam Sobanski",
    "Aleksandar Čebzan",
    "Aleksandar Čebzan",
    "Aleš Křivánek", 
    "Anton Duda",
    "Anton Duda",
    "Antonín Morawiec",
    "Boyan Atanasov",
    "Boyan Atanasov",
    "Boyan Atanasov",
    "Boyan Atanasov",
    "Boyan Atanasov",
    "Dana Voitle",
    "Daniela Vrbová",
    "Daniela Vrbová",
    "David Buchta",
    "David Polok",
    "David Tomiczek",
    "David Tomiczek",
    "Denisa Lungová",
    "Dita Vysoudilová",
    "Dominik Lanča",
    "Ekaterina Khludova",
    "Eva Fabiánková",
    "Eva Suchá",
    "Filip Šafránek",
    "Geena Alexander George",
    "Geena Alexandra George",
    "Hana Stefanov",
    "Honza Kašpárek", 
    "Ivo Hluchník",
    "Jakub Hurta",
    "Jakub Hurta",
    "Jakub Konarski",
    "Jakub Konarski",
    "Jan Fasanok",
    "Jan Korous",
    "Jan Korous",
    "Jan Korous",
    "Jan Korous",
    "Jana Hachemi",
    "Jana Hachemi", 
    "Jana Soviarova",
    "Jana Soviarova",
    "Jana Soviarova",
    "Jana Soviarová",
    "Jana Soviarová",
    "Jana Soviarová",
    "Jaroslav Vítek",
    "Jaroslav Vítek", 
    "Jaroslav Vítek", 
    "Jindřich Šonka",
    "Jirka Pavlinec", 
    "Jiří Bartusek", 
    "Jiří Galacz",
    "Jiří Hradil", 
    "Jiří Klimeš",
    "Jiří Kula",
    "Jiří Novák",
    "Jiří Potyš", 
    "Jiří Vodička",
    "Josef Řiháček",
    "Katarina Urbanová",
    "Kateřina Nová",
    "Klára Blechová",
    "Kristina Gabrišová",
    "Lenka Lodge Herdová",
    "Lucia Lajčáková", 
    "Lucie Horejsková",
    "Lucie Lajčáková",
    "Lukáš Hertl", 
    "Lukáš Krais",
    "Lukáš Krais", 
    "Lukáš Rucký",
    "Marek Knobloch",
    "Marek Mucha",
    "Marek Révay",
    "Martin Albert",
    "Martin Albert",
    "Martin Čapek",
    "Martin Čapek",
    "Martin Čapek",
    "Martin Greňo",
    "Martin Mišík",
    "Martin Remeň",
    "Michael Bik",
    "Michael Bik",
    "Michael Bik",
    "Michael Bik",
    "Michael Piňos",
    "Michaela Brandýsová",
    "Michaela Wilczková",
    "Michaela Zelinová",
    "Michal Bik",
    "Michal Bik",
    "Michal Bůžek",
    "Michal Novák", 
    "Miroslav Schnitta",
    "Moataz Saleh",
    "Moataz Saleh",
    "Mohamed Atef",
    "Mohamed Atef",
    "Mohamed Atef",
    "Mohamed Atef",
    "Monika Banotová",
    "Monika Banotová",
    "Nadia Merzougui", 
    "Nikol Vinklerová",
    "Nikola Bahrová",
    "Ondřej Konečný",
    "Patrik Donee",
    "Pavel Eschler",
    "Pavel Lepík",
    "Petr Kalman",
    "Petr Kaminsky",
    "Petr Kubát",
    "Petr Mazurek", 
    "Petr Sklenář",
    "Petr Szypka", 
    "Radka Šišková",
    "Radka Šišková",
    "Radomír Chwalek",
    "Radovan Čierny",
    "Radovan Číž",
    "Renata Skrlíková",
    "Renáta Škrlíková",
    "Robert Ramík",
    "Roman Liebertz",
    "Samuel Gabaj",
    "Shar Atul Hasan",
    "Simona Sítková",
    "Simona Sítková",
    "Simona Vaisová",
    "Simona Vaisová",
    "Simona Vaisová",
    "Táňa Vimmerová",
    "Tomas Skuta",
    "Tomáš Burda",
    "Tomáš Burda",
    "Tomáš Burda",
    "Tomáš Burda",
    "Tomáš Dočkal",
    "Tomáš Hlinovský",
    "Tomáš Kofránek",
    "Tomáš Kofránek", 
    "Tomáš Kolek",
    "Tomáš Mucha",
    "Tomáš Mucha",
    "Tomáš Mucha",
    "Tomáš Mucha",
    "Tomáš Seilder",
    "Tomáš Stehlík",
    "Tomáš Toběrný",
    "Vojtěch Kaniok",
    "Vojtěch Polášek",
    "Vojtěch Žurek",
    "Vojtěch Žurek",
    "Vojtěch Žurek",
    "Zuzana Kocmánková",
]

// Selectors
const candidatesButton = document.querySelector(".btn");
const candidates = document.querySelector(".candidates");

// Events
candidatesButton.addEventListener("click", getRandomCandidate);

// functions

function getRandomCandidate(event) {
    event.preventDefault();
    const randomNumber = Math.floor(Math.random() * names.length);  

    // Create LI
    const newCandidate = document.createElement("li");
    newCandidate.innerText = names[randomNumber];
    newCandidate.classList.add("newCandidate");

    // Append LI to UL
    candidates.appendChild(newCandidate);
    console.log(names);
    names.splice(randomNumber, 1)
}




